"""Initial nomenclature. Actual yields are entered, never inferred from anatomy."""
PRODUCTS = [
    ("live", "Живое животное", "live", True),
    ("carcass", "Туша", "meat", True),
    ("half", "Полутуша", "meat", True),
    ("tenderloin", "Вырезка ягнёнка", "meat", True),
    ("shoulder", "Лопатка ягнёнка", "meat", True),
    ("mince", "Фарш ягнёнка", "meat", False),
    ("side", "Бок ягнёнка", "meat", True),
    ("rack", "Каре ягнёнка", "meat", True),
    ("steak", "Стейк ягнёнка", "meat", True),
    ("shank", "Голень", "meat", True),
    ("leg", "Окорок", "meat", True),
    ("ribs", "Рёбра", "meat", True),
    ("lungs", "Лёгкие", "offal", True),
    ("liver", "Печень", "offal", True),
    ("kidneys", "Почки", "offal", True),
    ("testes", "Семенники", "offal", True),
    ("head", "Голова", "offal", True),
    ("heart", "Сердце", "offal", True),
]
