# Generated by Django 4.2.15 on 2026-10-08 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Приходная накладная'), ('consume', 'Расход кормов'), ('reversal', 'Сторно')], max_length=12)),
                ('state', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Подтверждён'), ('reversed', 'Сторнирован'), ('cancelled', 'Отменён')], default='draft', max_length=12)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='FeedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('hay', 'Сено / сенаж'), ('feed', 'Корма'), ('salt', 'Соль'), ('other', 'Прочее')], max_length=12)),
                ('unit', models.CharField(choices=[('kg', 'кг'), ('l', 'л'), ('pcs', 'шт.')], max_length=8)),
                ('package', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='FeedSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FeedVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('content', models.BinaryField(blank=True, default=bytes)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='feed_inventory.feeddocument')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='FeedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('lines', models.JSONField(default=list)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=40)),
                ('per_head', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='norms', to='feed_inventory.feedproduct')),
            ],
        ),
        migrations.CreateModel(
            name='FeedMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('packages', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='feed_inventory.feeddocument')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='feed_inventory.feedproduct')),
            ],
        ),
        migrations.AddField(
            model_name='feeddocument',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='feed_inventory.feedorder'),
        ),
        migrations.AddField(
            model_name='feeddocument',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_feed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeddocument',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='feed_inventory.feeddocument'),
        ),
        migrations.CreateModel(
            name='FeedAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='feedversion',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='feed_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='feednorm',
            constraint=models.UniqueConstraint(fields=('product', 'group'), name='feed_unique_norm'),
        ),
        migrations.AddConstraint(
            model_name='feednorm',
            constraint=models.CheckConstraint(check=models.Q(('per_head__gte', 0), ('per_head__isnull', True), _connector='OR'), name='feed_nonnegative_norm'),
        ),
        migrations.AddConstraint(
            model_name='feedmovement',
            constraint=models.UniqueConstraint(fields=('document', 'product'), name='feed_unique_movement'),
        ),
        migrations.AddConstraint(
            model_name='feeddocument',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'consume'), ('state', 'posted')), fields=('date',), name='feed_one_posted_consumption_per_day'),
        ),
    ]
