# Generated by Django 4.2.15 on 2026-10-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_inventory', '0002_initial_feed_norms'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedproduct',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='feeddocument',
            name='kind',
            field=models.CharField(choices=[('receipt', 'Приходная накладная'), ('consume', 'Расход кормов'), ('writeoff', 'Акт списания кормов'), ('reversal', 'Сторно')], max_length=12),
        ),
    ]
