# Generated by Django 4.1.1 on 2024-08-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheepfold', models.CharField(max_length=200, verbose_name='Овчарня')),
                ('compartment', models.CharField(max_length=200, verbose_name='Отсек')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(max_length=200, verbose_name='Название статуса')),
                ('date_of_status', models.DateField(verbose_name='Дата статуса')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=100, unique=True, verbose_name='Бирка')),
                ('animal_type', models.CharField(max_length=100, verbose_name='Тип животного')),
            ],
        ),
        migrations.CreateModel(
            name='VeterinaryCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(max_length=200, verbose_name='Тип ветобработки')),
            ],
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес (кг)')),
                ('weight_date', models.DateField(verbose_name='Дата взвешивания')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.tag', verbose_name='Бирка')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_care', models.DateField(verbose_name='Дата обработки')),
                ('medication', models.CharField(max_length=200, verbose_name='Препарат')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.place', verbose_name='Место')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.status', verbose_name='Статус')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='veterinary.tag', verbose_name='Бирка')),
                ('veterinary_care', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.veterinarycare', verbose_name='Тип ветобработки')),
            ],
        ),
    ]
