# Generated by Django 4.2.15 on 2024-08-26 20:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheepfold', models.CharField(max_length=200, verbose_name='Овчарня')),
                ('compartment', models.CharField(max_length=200, verbose_name='Отсек')),
                ('date_of_transfer', models.DateField(default=django.utils.timezone.now, verbose_name='Дата перевода')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(max_length=200, verbose_name='Название статуса')),
                ('date_of_status', models.DateField(default=django.utils.timezone.now, verbose_name='Дата статуса')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет статуса')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=100, unique=True, verbose_name='Бирка')),
                ('animal_type', models.CharField(max_length=100, verbose_name='Тип животного')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Дата выдачи бирки')),
            ],
        ),
        migrations.CreateModel(
            name='VeterinaryCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('VACCINATION', 'Вакцинация'), ('HAIRCUT', 'Стрижка'), ('PEST_CONTROL', 'Обработка от паразитов'), ('MEDICAL_TREATMENT', 'Лечение'), ('OTHER', 'Прочее')], max_length=50, verbose_name='Тип обработки')),
                ('care_name', models.CharField(max_length=200, verbose_name='Название обработки')),
                ('medication', models.CharField(blank=True, max_length=200, null=True, verbose_name='Препарат/материал')),
                ('purpose', models.CharField(blank=True, max_length=200, null=True, verbose_name='Цель обработки')),
            ],
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес (кг)')),
                ('weight_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата взвешивания')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.tag', verbose_name='Бирка')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_care', models.DateField(default=django.utils.timezone.now, verbose_name='Дата обработки')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.place', verbose_name='Место')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.status', verbose_name='Статус')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.tag', verbose_name='Бирка')),
                ('veterinary_care', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.veterinarycare', verbose_name='Тип ветобработки')),
            ],
            options={
                'unique_together': {('tag', 'veterinary_care', 'date_of_care')},
            },
        ),
    ]
