# Generated by Django 5.2.4 on 2025-08-04 00:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sheepfold",
                    models.CharField(max_length=200, verbose_name="Овчарня-Отсек"),
                ),
                (
                    "date_of_transfer",
                    models.DateField(
                        default=datetime.date(2025, 8, 4), verbose_name="Дата перевода"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_type",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Название статуса"
                    ),
                ),
                (
                    "date_of_status",
                    models.DateField(
                        default=datetime.date(2025, 8, 4), verbose_name="Дата статуса"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#FFFFFF",
                        max_length=7,
                        unique=True,
                        verbose_name="Цвет статуса",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag_number",
                    models.CharField(max_length=100, unique=True, verbose_name="Бирка"),
                ),
                (
                    "animal_type",
                    models.CharField(max_length=100, verbose_name="Тип животного"),
                ),
                (
                    "issue_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата выдачи бирки"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_status",
                        to="veterinary.status",
                        verbose_name="Новый статус",
                    ),
                ),
                (
                    "old_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="old_status",
                        to="veterinary.status",
                        verbose_name="Старый статус",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="veterinary.tag",
                        verbose_name="Бирка",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VeterinaryCare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "care_type",
                    models.CharField(max_length=100, verbose_name="Тип обработки"),
                ),
                (
                    "care_name",
                    models.CharField(max_length=200, verbose_name="Название обработки"),
                ),
                (
                    "medication",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Препарат/материал",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Цель обработки",
                    ),
                ),
            ],
            options={
                "unique_together": {("care_type", "care_name", "medication")},
            },
        ),
        migrations.CreateModel(
            name="WeightRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Вес (кг)"
                    ),
                ),
                (
                    "weight_date",
                    models.DateField(
                        default=datetime.date(2025, 8, 4),
                        verbose_name="Дата взвешивания",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veterinary.tag",
                        verbose_name="Бирка",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="place_movements_to",
                        to="veterinary.place",
                        verbose_name="Новое место",
                    ),
                ),
                (
                    "old_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="place_movements_from",
                        to="veterinary.place",
                        verbose_name="Предыдущее место",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_movements",
                        to="veterinary.tag",
                        verbose_name="Бирка",
                    ),
                ),
            ],
            options={
                "unique_together": {("tag", "old_place", "new_place")},
            },
        ),
        migrations.CreateModel(
            name="Veterinary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_care",
                    models.DateField(
                        default=datetime.date(2025, 8, 4), verbose_name="Дата обработки"
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Примечания"),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veterinary.tag",
                        verbose_name="Бирка",
                    ),
                ),
                (
                    "veterinary_care",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="veterinary.veterinarycare",
                        verbose_name="Вет-обработка",
                    ),
                ),
            ],
            options={
                "unique_together": {("tag", "veterinary_care", "date_of_care")},
            },
        ),
    ]
