# Generated by Django 4.2.15 on 2024-12-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinary',
            name='place',
        ),
        migrations.RemoveField(
            model_name='veterinary',
            name='status',
        ),
    ]
