# Generated by Django 4.2.15 on 2024-09-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, unique=True, verbose_name='Цвет статуса'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_type',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название статуса'),
        ),
    ]
