# Generated by Django 4.2.15 on 2025-08-24 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='date_of_transfer',
            field=models.DateField(default=datetime.date(2025, 8, 24), verbose_name='Дата перевода'),
        ),
        migrations.AlterField(
            model_name='status',
            name='date_of_status',
            field=models.DateField(default=datetime.date(2025, 8, 24), verbose_name='Дата статуса'),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='date_of_care',
            field=models.DateField(default=datetime.date(2025, 8, 24), verbose_name='Дата обработки'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='weight_date',
            field=models.DateField(default=datetime.date(2025, 8, 24), verbose_name='Дата взвешивания'),
        ),
    ]
