# Generated by Django 4.1.1 on 2024-08-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date_of_status',
            field=models.DateField(auto_now_add=True, verbose_name='Дата статуса'),
        ),
    ]
