# Generated by Django 4.2.15 on 2024-09-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0002_alter_status_color_alter_status_status_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarycare',
            name='care_type',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тип обработки'),
        ),
    ]
