# Generated by Django 4.2.15 on 2024-09-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0003_alter_veterinarycare_care_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarycare',
            name='care_type',
            field=models.CharField(max_length=100, verbose_name='Тип обработки'),
        ),
        migrations.AlterUniqueTogether(
            name='veterinarycare',
            unique_together={('care_type', 'care_name', 'medication')},
        ),
    ]
