# Generated by Django 4.2.15 on 2025-09-26 14:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0003_alter_place_date_of_transfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='date_of_transfer',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата перевода'),
        ),
        migrations.AlterField(
            model_name='place',
            name='sheepfold',
            field=models.CharField(max_length=200, unique=True, verbose_name='Овчарня-Отсек'),
        ),
        migrations.AlterField(
            model_name='status',
            name='date_of_status',
            field=models.DateField(default=datetime.date(2025, 9, 26), verbose_name='Дата статуса'),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='date_of_care',
            field=models.DateField(default=datetime.date(2025, 9, 26), verbose_name='Дата обработки'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='weight_date',
            field=models.DateField(default=datetime.date(2025, 9, 26), verbose_name='Дата взвешивания'),
        ),
    ]
