# Generated by Django 4.2.15 on 2025-09-28 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0004_alter_place_date_of_transfer_alter_place_sheepfold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет статуса'),
        ),
        migrations.AlterField(
            model_name='status',
            name='date_of_status',
            field=models.DateField(default=datetime.date(2025, 9, 28), verbose_name='Дата статуса'),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='date_of_care',
            field=models.DateField(default=datetime.date(2025, 9, 28), verbose_name='Дата обработки'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='weight_date',
            field=models.DateField(default=datetime.date(2025, 9, 28), verbose_name='Дата взвешивания'),
        ),
    ]
