# Generated by Django 4.2.15 on 2025-12-18 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0005_alter_status_color_alter_status_date_of_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='veterinary',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='status',
            name='date_of_status',
            field=models.DateField(default=datetime.date(2025, 12, 18), verbose_name='Дата статуса'),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='date_of_care',
            field=models.DateField(default=datetime.date(2025, 12, 18), verbose_name='Дата обработки'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='weight_date',
            field=models.DateField(default=datetime.date(2025, 12, 18), verbose_name='Дата взвешивания'),
        ),
    ]
