# Generated by Django 4.2.15 on 2025-12-22 01:24

import begunici.app_types.veterinary.vet_models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0006_remove_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='date_of_transfer',
            field=models.DateField(default=begunici.app_types.veterinary.vet_models.get_current_date, verbose_name='Дата перевода'),
        ),
        migrations.AlterField(
            model_name='status',
            name='date_of_status',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время статуса'),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='date_of_care',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время обработки'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='weight_date',
            field=models.DateField(default=begunici.app_types.veterinary.vet_models.get_current_date, verbose_name='Дата взвешивания'),
        ),
    ]
