# Generated by Django 4.2.15 on 2025-12-22 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0007_alter_place_date_of_transfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='date_of_transfer',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время перевода'),
        ),
    ]
