# Generated by Django 4.2.15 on 2025-12-22 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0008_alter_place_date_of_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='statushistory',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время изменения'),
        ),
    ]
