# Generated by Django 4.2.15 on 2026-02-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0009_statushistory_change_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinary',
            name='duration_days',
            field=models.PositiveIntegerField(default=0, help_text='0 = бессрочно', verbose_name='Срок действия (дней)'),
        ),
    ]
