# Generated by Django 4.2.15 on 2026-02-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0010_veterinary_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarycare',
            name='default_duration_days',
            field=models.PositiveIntegerField(default=0, help_text='0 = бессрочно', verbose_name='Срок действия (дней)'),
        ),
    ]
