# Generated by Django 4.2.15 on 2026-02-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0011_veterinarycare_default_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinary',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Скрыть из таблицы текущих ветобработок', verbose_name='Скрыто из отслеживания'),
        ),
    ]
