# Generated by Django 4.2.15 on 2026-02-14 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0012_veterinary_is_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placemovement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='placemovement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='placemovement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время перемещения'),
        ),
    ]
