# Generated by Django 4.2.15 on 2026-03-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0014_remove_status_date_of_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='sheepfold',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Овчарня-Отсек'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_type',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название статуса'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='animal_type',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Тип животного'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_number',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Бирка'),
        ),
    ]
