# Generated by Django 4.2.15 on 2026-03-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0015_alter_place_sheepfold_alter_status_status_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['animal_type', 'tag_number'], name='tag_type_number_idx'),
        ),
    ]
