# Generated by Django 4.2.15 on 2026-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0016_add_tag_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veterinarycare",
            name="care_name",
            field=models.CharField(
                choices=[
                    ("Иммунизация", "Иммунизация"),
                    ("Антигельминтная", "Антигельминтная"),
                    ("Противопротозойная", "Противопротозойная"),
                    ("Дезинсекция", "Дезинсекция"),
                ],
                default="Иммунизация",
                max_length=200,
                verbose_name="Класс ветобработки",
            ),
        ),
        migrations.AlterField(
            model_name="veterinarycare",
            name="care_type",
            field=models.CharField(
                choices=[
                    ("Вакцинация", "Вакцинация"),
                    ("Противопаразитарная", "Противопаразитарная"),
                ],
                default="Вакцинация",
                max_length=100,
                verbose_name="Тип ветобработки",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="veterinarycare",
            unique_together={("care_type", "care_name", "medication", "purpose")},
        ),
    ]
