# Generated by Django 4.2.15 on 2026-06-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0018_veterinarycare_other_class_custom_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='date_of_transfer',
        ),
    ]
