# Generated by Django 4.2.15 on 2026-10-03 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0019_remove_place_date_of_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarnCalculatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barn_number', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Номер овчарни')),
                ('parameters', models.JSONField(default=dict, verbose_name='Параметры калькулятора')),
                ('manual_composition', models.JSONField(default=dict, verbose_name='Ручная компоновка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Параметры калькулятора овчарни',
                'verbose_name_plural': 'Параметры калькулятора овчарен',
                'ordering': ['barn_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='barncalculatorprofile',
            constraint=models.CheckConstraint(check=models.Q(('barn_number__gte', 1), ('barn_number__lte', 4)), name='barn_calculator_number_1_to_4'),
        ),
    ]
