# Generated by Django 4.2.15 on 2024-08-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст (в месяцах)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес (кг)')),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=10, verbose_name='Пол')),
                ('animal_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.status', verbose_name='Статус')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='veterinary.tag', verbose_name='Бирка')),
                ('weight_records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_weight_records', to='veterinary.weightrecord', verbose_name='История взвешиваний')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст (в месяцах)')),
                ('mother_tag', models.CharField(max_length=200, verbose_name='Бирка матери')),
                ('father_tag', models.CharField(max_length=200, verbose_name='Бирка отца')),
                ('replace_date', models.DateField(verbose_name='Дата перевода')),
                ('last_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Последний вес')),
                ('last_weight_date', models.DateField(verbose_name='Дата последнего взвешивания')),
                ('maker_tag', models.CharField(max_length=200, verbose_name='Производитель на окот')),
                ('planned_salary', models.DateField(verbose_name='Планируемая дата окота')),
                ('fact_salary', models.DateField(verbose_name='Фактическая дата окота')),
                ('lamb_count', models.IntegerField(verbose_name='Число ягнят')),
                ('lamb_tag', models.CharField(max_length=200, verbose_name='Бирки ягнят')),
                ('animal_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.status', verbose_name='Статус')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.place', verbose_name='Место')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='veterinary.tag', verbose_name='Бирка')),
                ('veterinary_care', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.veterinarycare', verbose_name='Последняя ветобработка')),
                ('weight_records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_weight_records', to='veterinary.weightrecord', verbose_name='История взвешиваний')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст (в месяцах)')),
                ('mother_tag', models.CharField(max_length=200, verbose_name='Бирка матери')),
                ('father_tag', models.CharField(max_length=200, verbose_name='Бирка отца')),
                ('replace_date', models.DateField(verbose_name='Дата перевода')),
                ('last_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Последний вес')),
                ('last_weight_date', models.DateField(verbose_name='Дата последнего взвешивания')),
                ('animal_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.status', verbose_name='Статус')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.place', verbose_name='Место')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='veterinary.tag', verbose_name='Бирка')),
                ('veterinary_care', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.veterinarycare', verbose_name='Последняя ветобработка')),
                ('weight_records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_weight_records', to='veterinary.weightrecord', verbose_name='История взвешиваний')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст (в месяцах)')),
                ('plemstatus', models.CharField(max_length=200, verbose_name='Племенной статус')),
                ('last_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Последний вес')),
                ('last_weight_date', models.DateField(verbose_name='Дата последнего взвешивания')),
                ('working_condition', models.CharField(max_length=200, verbose_name='Рабочее состояние')),
                ('animal_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.status', verbose_name='Статус')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.place', verbose_name='Место')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='veterinary.tag', verbose_name='Бирка')),
                ('veterinary_care', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.veterinarycare', verbose_name='Последняя ветобработка')),
                ('weight_records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_weight_records', to='veterinary.weightrecord', verbose_name='История взвешиваний')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lambing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mating_date', models.DateField(verbose_name='Дата постановки под барана')),
                ('estimated_lambing_date', models.DateField(verbose_name='Ориентировочная дата окота')),
                ('actual_lambing_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата окота')),
                ('lamb_count', models.IntegerField(verbose_name='Число ягнят')),
                ('lambs', models.ManyToManyField(to='animals.lamb', verbose_name='Ягнята')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.maker', verbose_name='Производитель')),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.sheep', verbose_name='Овца')),
            ],
        ),
        migrations.CreateModel(
            name='Ewe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст (в месяцах)')),
                ('mother_tag', models.CharField(max_length=200, verbose_name='Бирка матери')),
                ('father_tag', models.CharField(max_length=200, verbose_name='Бирка отца')),
                ('replace_date', models.DateField(verbose_name='Дата перевода')),
                ('last_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Последний вес')),
                ('last_weight_date', models.DateField(verbose_name='Дата последнего взвешивания')),
                ('animal_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.status', verbose_name='Статус')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.place', verbose_name='Место')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='veterinary.tag', verbose_name='Бирка')),
                ('veterinary_care', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.veterinarycare', verbose_name='Последняя ветобработка')),
                ('weight_records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_weight_records', to='veterinary.weightrecord', verbose_name='История взвешиваний')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
