# Generated by Django 4.2.15 on 2025-08-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ewe',
            options={'verbose_name': 'Ярка', 'verbose_name_plural': 'Ярки'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': 'Баран', 'verbose_name_plural': 'Бараны'},
        ),
        migrations.AlterModelOptions(
            name='sheep',
            options={'verbose_name': 'Овца', 'verbose_name_plural': 'Овцы'},
        ),
        migrations.AddField(
            model_name='sheep',
            name='planned_lambing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемая дата окота'),
        ),
    ]
