# Generated by Django 4.2.15 on 2024-11-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewe',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='ewe',
            name='veterinary_history',
            field=models.ManyToManyField(blank=True, to='veterinary.veterinary', verbose_name='История ветобработок'),
        ),
        migrations.AlterField(
            model_name='ewe',
            name='weight_records',
            field=models.ManyToManyField(blank=True, to='veterinary.weightrecord', verbose_name='История взвешиваний'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='veterinary_history',
            field=models.ManyToManyField(blank=True, to='veterinary.veterinary', verbose_name='История ветобработок'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='weight_records',
            field=models.ManyToManyField(blank=True, to='veterinary.weightrecord', verbose_name='История взвешиваний'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='veterinary_history',
            field=models.ManyToManyField(blank=True, to='veterinary.veterinary', verbose_name='История ветобработок'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='weight_records',
            field=models.ManyToManyField(blank=True, to='veterinary.weightrecord', verbose_name='История взвешиваний'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='veterinary_history',
            field=models.ManyToManyField(blank=True, to='veterinary.veterinary', verbose_name='История ветобработок'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='weight_records',
            field=models.ManyToManyField(blank=True, to='veterinary.weightrecord', verbose_name='История взвешиваний'),
        ),
    ]
