# Generated by Django 4.2.15 on 2024-12-25 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_maker_father_alter_maker_mother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_father', to='animals.maker', verbose_name='Отец'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_mother', to='animals.maker', verbose_name='Мать'),
        ),
    ]
