# Generated by Django 4.2.15 on 2024-11-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_ewe_place_alter_ewe_veterinary_history_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ewe',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sheep',
            options={'ordering': ['id']},
        ),
    ]
