# Generated by Django 4.2.15 on 2025-12-22 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0007_alter_place_date_of_transfer_and_more'),
        ('animals', '0003_remove_redundant_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewe',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_children_father', to='veterinary.tag', verbose_name='Отец'),
        ),
        migrations.AlterField(
            model_name='ewe',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_children_mother', to='veterinary.tag', verbose_name='Мать'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_children_father', to='veterinary.tag', verbose_name='Отец'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_children_mother', to='veterinary.tag', verbose_name='Мать'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_children_father', to='veterinary.tag', verbose_name='Отец'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_children_mother', to='veterinary.tag', verbose_name='Мать'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_children_father', to='veterinary.tag', verbose_name='Отец'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_children_mother', to='veterinary.tag', verbose_name='Мать'),
        ),
    ]
