# Generated by Django 4.2.15 on 2024-11-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_ewe_options_alter_lambing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lambing',
            options={'verbose_name': 'Окот', 'verbose_name_plural': 'Окоты'},
        ),
        migrations.AlterModelOptions(
            name='maker',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
    ]
