# Generated by Django 4.2.15 on 2025-12-22 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_ewe_father_alter_ewe_mother_alter_maker_father_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lambing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='lambing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный окот'),
        ),
        migrations.AddField(
            model_name='lambing',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='lambing',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lambings_as_father', to='animals.ram', verbose_name='Баран (Отец)'),
        ),
        migrations.AddField(
            model_name='lambing',
            name='sheep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lambings', to='animals.sheep', verbose_name='Овца (Мать)'),
        ),
        migrations.AddField(
            model_name='lambing',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала окота (случки)'),
        ),
        migrations.AlterField(
            model_name='lambing',
            name='ewe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lambings', to='animals.ewe', verbose_name='Ярка (Мать)'),
        ),
        migrations.AlterField(
            model_name='lambing',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lambings_as_father', to='animals.maker', verbose_name='Производитель (Отец)'),
        ),
        migrations.AlterField(
            model_name='lambing',
            name='planned_lambing_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Планируемая дата окота'),
        ),
    ]
