# Generated by Django 4.2.15 on 2026-01-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_lambing_created_at_lambing_is_active_lambing_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата заметки')),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заметка календаря',
                'verbose_name_plural': 'Заметки календаря',
                'ordering': ['-date'],
            },
        ),
    ]
