# Generated by Django 4.2.15 on 2026-02-13 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0006_calendarnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='Тип действия')),
                ('object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип объекта')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID объекта')),
                ('description', models.TextField(verbose_name='Описание действия')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время действия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('additional_data', models.JSONField(blank=True, null=True, verbose_name='Дополнительные данные')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действий пользователя',
                'verbose_name_plural': 'Логи действий пользователей',
                'ordering': ['-timestamp'],
            },
        ),
    ]
