# Generated by Django 4.2.15 on 2026-03-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_useractionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewe',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Примечание'),
        ),
    ]
