# Generated by Django 4.2.15 on 2026-03-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_increase_note_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewe',
            name='father',
            field=models.CharField(blank=True, help_text='Номер бирки отца (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Отец (номер бирки)'),
        ),
        migrations.AlterField(
            model_name='ewe',
            name='mother',
            field=models.CharField(blank=True, help_text='Номер бирки матери (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Мать (номер бирки)'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='father',
            field=models.CharField(blank=True, help_text='Номер бирки отца (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Отец (номер бирки)'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='mother',
            field=models.CharField(blank=True, help_text='Номер бирки матери (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Мать (номер бирки)'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='father',
            field=models.CharField(blank=True, help_text='Номер бирки отца (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Отец (номер бирки)'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='mother',
            field=models.CharField(blank=True, help_text='Номер бирки матери (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Мать (номер бирки)'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='father',
            field=models.CharField(blank=True, help_text='Номер бирки отца (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Отец (номер бирки)'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='mother',
            field=models.CharField(blank=True, help_text='Номер бирки матери (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Мать (номер бирки)'),
        ),
    ]
