# Generated by Django 4.2.15 on 2026-03-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_change_parents_to_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewe',
            name='rshn_tag',
            field=models.CharField(blank=True, help_text='Уникальный номер бирки РСХН (необязательно)', max_length=50, null=True, unique=True, verbose_name='Бирка РСХН'),
        ),
        migrations.AddField(
            model_name='maker',
            name='rshn_tag',
            field=models.CharField(blank=True, help_text='Уникальный номер бирки РСХН (необязательно)', max_length=50, null=True, unique=True, verbose_name='Бирка РСХН'),
        ),
        migrations.AddField(
            model_name='ram',
            name='rshn_tag',
            field=models.CharField(blank=True, help_text='Уникальный номер бирки РСХН (необязательно)', max_length=50, null=True, unique=True, verbose_name='Бирка РСХН'),
        ),
        migrations.AddField(
            model_name='sheep',
            name='rshn_tag',
            field=models.CharField(blank=True, help_text='Уникальный номер бирки РСХН (необязательно)', max_length=50, null=True, unique=True, verbose_name='Бирка РСХН'),
        ),
    ]
