# Generated by Django 4.2.15 on 2026-03-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_add_rshn_tag_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewe',
            name='date_otbivka',
            field=models.DateField(blank=True, help_text='Дата отбивки животного (необязательно)', null=True, verbose_name='Дата отбивки'),
        ),
        migrations.AddField(
            model_name='maker',
            name='date_otbivka',
            field=models.DateField(blank=True, help_text='Дата отбивки животного (необязательно)', null=True, verbose_name='Дата отбивки'),
        ),
        migrations.AddField(
            model_name='ram',
            name='date_otbivka',
            field=models.DateField(blank=True, help_text='Дата отбивки животного (необязательно)', null=True, verbose_name='Дата отбивки'),
        ),
        migrations.AddField(
            model_name='sheep',
            name='date_otbivka',
            field=models.DateField(blank=True, help_text='Дата отбивки животного (необязательно)', null=True, verbose_name='Дата отбивки'),
        ),
    ]
