# Generated by Django 4.2.15 on 2026-03-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_add_mother_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='maker',
            name='name',
            field=models.CharField(blank=True, help_text='Уникальное имя производителя (необязательно)', max_length=50, null=True, unique=True, verbose_name='Имя'),
        ),
    ]
