# Generated by Django 4.2.15 on 2026-03-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0013_add_name_field_to_maker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewe',
            name='birth_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='ewe',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='birth_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='birth_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='birth_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В архиве'),
        ),
    ]
