# Generated by Django 4.2.15 on 2026-03-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_alter_ewe_birth_date_alter_ewe_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewe',
            name='father',
            field=models.CharField(blank=True, db_index=True, help_text='Номер бирки отца (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Отец (номер бирки)'),
        ),
        migrations.AlterField(
            model_name='ewe',
            name='mother',
            field=models.CharField(blank=True, db_index=True, help_text='Номер бирки матери (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Мать (номер бирки)'),
        ),
        migrations.AlterField(
            model_name='ewe',
            name='rshn_tag',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный номер бирки РСХН (необязательно)', max_length=50, null=True, unique=True, verbose_name='Бирка РСХН'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='father',
            field=models.CharField(blank=True, db_index=True, help_text='Номер бирки отца (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Отец (номер бирки)'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='mother',
            field=models.CharField(blank=True, db_index=True, help_text='Номер бирки матери (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Мать (номер бирки)'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='rshn_tag',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный номер бирки РСХН (необязательно)', max_length=50, null=True, unique=True, verbose_name='Бирка РСХН'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='father',
            field=models.CharField(blank=True, db_index=True, help_text='Номер бирки отца (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Отец (номер бирки)'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='mother',
            field=models.CharField(blank=True, db_index=True, help_text='Номер бирки матери (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Мать (номер бирки)'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='rshn_tag',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный номер бирки РСХН (необязательно)', max_length=50, null=True, unique=True, verbose_name='Бирка РСХН'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='father',
            field=models.CharField(blank=True, db_index=True, help_text='Номер бирки отца (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Отец (номер бирки)'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='mother',
            field=models.CharField(blank=True, db_index=True, help_text='Номер бирки матери (буквы и цифры без пробелов)', max_length=50, null=True, verbose_name='Мать (номер бирки)'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='rshn_tag',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный номер бирки РСХН (необязательно)', max_length=50, null=True, unique=True, verbose_name='Бирка РСХН'),
        ),
    ]
