# Generated by Django 4.2.15 on 2026-04-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0015_add_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewe',
            name='dorper_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Процент дорперности (0-100%)', max_digits=5, null=True, verbose_name='Дорперность (%)'),
        ),
        migrations.AddField(
            model_name='ewe',
            name='is_manual_dorper',
            field=models.BooleanField(default=False, help_text='Указывает, была ли дорперность задана вручную или рассчитана автоматически', verbose_name='Дорперность задана вручную'),
        ),
        migrations.AddField(
            model_name='maker',
            name='dorper_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Процент дорперности (0-100%)', max_digits=5, null=True, verbose_name='Дорперность (%)'),
        ),
        migrations.AddField(
            model_name='maker',
            name='is_manual_dorper',
            field=models.BooleanField(default=False, help_text='Указывает, была ли дорперность задана вручную или рассчитана автоматически', verbose_name='Дорперность задана вручную'),
        ),
        migrations.AddField(
            model_name='ram',
            name='dorper_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Процент дорперности (0-100%)', max_digits=5, null=True, verbose_name='Дорперность (%)'),
        ),
        migrations.AddField(
            model_name='ram',
            name='is_manual_dorper',
            field=models.BooleanField(default=False, help_text='Указывает, была ли дорперность задана вручную или рассчитана автоматически', verbose_name='Дорперность задана вручную'),
        ),
        migrations.AddField(
            model_name='sheep',
            name='dorper_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Процент дорперности (0-100%)', max_digits=5, null=True, verbose_name='Дорперность (%)'),
        ),
        migrations.AddField(
            model_name='sheep',
            name='is_manual_dorper',
            field=models.BooleanField(default=False, help_text='Указывает, была ли дорперность задана вручную или рассчитана автоматически', verbose_name='Дорперность задана вручную'),
        ),
    ]
