# Generated by Django 4.2.15 on 2026-04-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0016_ewe_dorper_percentage_ewe_is_manual_dorper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewe',
            name='dorper_percentage',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Процент дорперности (0-100%)', max_digits=8, null=True, verbose_name='Дорперность (%)'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='dorper_percentage',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Процент дорперности (0-100%)', max_digits=8, null=True, verbose_name='Дорперность (%)'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='dorper_percentage',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Процент дорперности (0-100%)', max_digits=8, null=True, verbose_name='Дорперность (%)'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='dorper_percentage',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Процент дорперности (0-100%)', max_digits=8, null=True, verbose_name='Дорперность (%)'),
        ),
    ]
