# Generated by Django 4.2.15 on 2026-04-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0017_alter_dorper_percentage_precision"),
    ]

    operations = [
        migrations.AddField(
            model_name="ewe",
            name="carcass_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="\u0417\u0430\u043f\u043e\u043b\u043d\u044f\u0435\u0442\u0441\u044f \u043f\u0440\u0438 \u0430\u0440\u0445\u0438\u0432\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0438 \u0436\u0438\u0432\u043e\u0442\u043d\u043e\u0433\u043e",
                max_digits=6,
                null=True,
                verbose_name="\u0412\u0435\u0441 \u0442\u0443\u0448\u0438 (\u043a\u0433)",
            ),
        ),
        migrations.AddField(
            model_name="maker",
            name="carcass_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="\u0417\u0430\u043f\u043e\u043b\u043d\u044f\u0435\u0442\u0441\u044f \u043f\u0440\u0438 \u0430\u0440\u0445\u0438\u0432\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0438 \u0436\u0438\u0432\u043e\u0442\u043d\u043e\u0433\u043e",
                max_digits=6,
                null=True,
                verbose_name="\u0412\u0435\u0441 \u0442\u0443\u0448\u0438 (\u043a\u0433)",
            ),
        ),
        migrations.AddField(
            model_name="ram",
            name="carcass_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="\u0417\u0430\u043f\u043e\u043b\u043d\u044f\u0435\u0442\u0441\u044f \u043f\u0440\u0438 \u0430\u0440\u0445\u0438\u0432\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0438 \u0436\u0438\u0432\u043e\u0442\u043d\u043e\u0433\u043e",
                max_digits=6,
                null=True,
                verbose_name="\u0412\u0435\u0441 \u0442\u0443\u0448\u0438 (\u043a\u0433)",
            ),
        ),
        migrations.AddField(
            model_name="sheep",
            name="carcass_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="\u0417\u0430\u043f\u043e\u043b\u043d\u044f\u0435\u0442\u0441\u044f \u043f\u0440\u0438 \u0430\u0440\u0445\u0438\u0432\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0438 \u0436\u0438\u0432\u043e\u0442\u043d\u043e\u0433\u043e",
                max_digits=6,
                null=True,
                verbose_name="\u0412\u0435\u0441 \u0442\u0443\u0448\u0438 (\u043a\u0433)",
            ),
        ),
    ]
