# Generated by Django 4.2.15 on 2026-05-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0018_add_carcass_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="lambing",
            name="dead_lambs_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="\u0415\u0441\u043b\u0438 \u043d\u0435 \u0443\u043a\u0430\u0437\u0430\u043d\u043e, \u0441\u0447\u0438\u0442\u0430\u0435\u0442\u0441\u044f 0",
                verbose_name="\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043c\u0435\u0440\u0442\u0432\u044b\u0445 \u044f\u0433\u043d\u044f\u0442",
            ),
        ),
    ]
