# Generated by Django 4.2.15 on 2026-05-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0019_lambing_dead_lambs_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftTransferNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Дата")),
                ("text", models.TextField(verbose_name="Текст заметки")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Заметка передачи смены",
                "verbose_name_plural": "Заметки передачи смены",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
