# Generated by Django 4.2.15 on 2026-10-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0032_temporarytag_animal_needs_retagging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ewe',
            name='age',
        ),
        migrations.RemoveField(
            model_name='maker',
            name='age',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='age',
        ),
        migrations.RemoveField(
            model_name='sheep',
            name='age',
        ),
    ]
