# Generated by Django 4.2.15 on 2026-10-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0033_remove_cached_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewe',
            name='is_for_sale',
            field=models.BooleanField(db_index=True, default=False, help_text='Отдельная отметка назначения животного, не статус.', verbose_name='К продаже'),
        ),
        migrations.AddField(
            model_name='maker',
            name='is_for_sale',
            field=models.BooleanField(db_index=True, default=False, help_text='Отдельная отметка назначения животного, не статус.', verbose_name='К продаже'),
        ),
        migrations.AddField(
            model_name='ram',
            name='is_for_sale',
            field=models.BooleanField(db_index=True, default=False, help_text='Отдельная отметка назначения животного, не статус.', verbose_name='К продаже'),
        ),
        migrations.AddField(
            model_name='sheep',
            name='is_for_sale',
            field=models.BooleanField(db_index=True, default=False, help_text='Отдельная отметка назначения животного, не статус.', verbose_name='К продаже'),
        ),
    ]
