# Generated by Django 4.2.15 on 2026-10-04 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_tag_id', models.PositiveBigIntegerField(unique=True)),
                ('animal_type', models.CharField(max_length=10)),
                ('tag_number', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=10)),
                ('archive_date', models.DateField()),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sp54', 'СП-54'), ('sp55', 'СП-55'), ('invoice', 'Товарная накладная')], max_length=10)),
                ('state', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'На проверке'), ('confirmed', 'Подтверждён'), ('reversed', 'Сторнирован')], default='draft', max_length=12)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('payload', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_confirmations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('live', 'Живьём'), ('meat', 'Мясо')], max_length=10)),
                ('customer', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('required_heads', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('open', 'Открыта'), ('partial', 'Частично выполнена'), ('fulfilled', 'Выполнена'), ('closed', 'Закрыта')], default='open', max_length=12)),
                ('external_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('sex', models.CharField(blank=True, choices=[('', 'Любой'), ('male', 'Самец'), ('female', 'Самка')], max_length=6)),
                ('age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('purity_min', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('purity_max', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('live', 'Животное'), ('meat', 'Мясо'), ('offal', 'Субпродукт')], max_length=10)),
                ('counted', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.animalcase')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.stocklot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Приход'), ('sale', 'Реализация'), ('reversal', 'Сторно'), ('cut_in', 'Выход разделки'), ('cut_out', 'Передано в разделку')], max_length=12)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity', models.IntegerField(default=0)),
                ('operation', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.document')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stocklot')),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.orderline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=180)),
                ('content_type', models.CharField(max_length=100)),
                ('content', models.BinaryField()),
                ('sha256', models.CharField(max_length=64)),
                ('snapshot', models.JSONField(default=dict)),
                ('origin', models.CharField(default='generated', max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='inventory.document')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.order'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.document')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.order')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='animalcase',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='inventory.document'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(check=models.Q(('weight', 0), _negated=True), name='inventory_movement_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('document', 'lot', 'kind'), name='inventory_document_lot_kind_unique'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(check=models.Q(('weight__gte', 0), models.Q(('weight__gt', 0), ('quantity__gt', 0), _connector='OR')), name='inventory_order_line_positive'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='inventory_document_version_unique'),
        ),
    ]
