# Generated by Django 4.2.15 on 2026-10-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='animal_type',
            field=models.CharField(blank=True, choices=[('maker', 'Баран-производитель'), ('ram', 'Баранчик'), ('ewe', 'Ярка'), ('sheep', 'Овцематка')], default='', max_length=10),
        ),
    ]
