# Generated by Django 4.2.15 on 2026-10-10 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veterinary', '0020_barn_calculator_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Приходная накладная'), ('consume', 'Прочий расход препаратов'), ('treatment', 'Расход по ветобработке'), ('writeoff', 'Акт списания препаратов'), ('reversal', 'Сторно')], max_length=12)),
                ('state', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Подтверждён'), ('reversed', 'Сторнирован'), ('cancelled', 'Отменён')], default='draft', max_length=12)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vet_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='VetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('medicine', 'Препарат'), ('vaccine', 'Вакцина'), ('material', 'Материал'), ('other', 'Прочее')], max_length=12)),
                ('unit', models.CharField(choices=[('ml', 'мл'), ('g', 'г'), ('pcs', 'шт.'), ('dose', 'доз'), ('l', 'л'), ('kg', 'кг')], max_length=8)),
                ('package', models.CharField(blank=True, max_length=40)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='VetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('legacy_treatment_id', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('content', models.BinaryField(blank=True, default=bytes)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='vet_inventory.vetdocument')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='VetTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveBigIntegerField(unique=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('calculation', models.JSONField(default=dict)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, null=True)),
                ('state', models.CharField(choices=[('pending', 'Требует сверки'), ('posted', 'Учтён'), ('excluded', 'Без расхода'), ('deleted', 'Обработка удалена')], default='pending', max_length=12)),
                ('issue', models.TextField(blank=True)),
                ('manual', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vet_inventory.vetdocument')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vet_inventory.vetproduct')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='VetOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('lines', models.JSONField(default=list)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VetNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('head', 'На голову'), ('weight', 'На 1 кг веса'), ('bands', 'По диапазонам веса')], max_length=12)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('bands', models.JSONField(default=list)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('care', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_norm', to='veterinary.veterinarycare')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='norms', to='vet_inventory.vetproduct')),
            ],
        ),
        migrations.CreateModel(
            name='VetMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('packages', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='vet_inventory.vetdocument')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='vet_inventory.vetproduct')),
            ],
        ),
        migrations.AddField(
            model_name='vetdocument',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vet_inventory.vetorder'),
        ),
        migrations.AddField(
            model_name='vetdocument',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_vet_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vetdocument',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vet_inventory.vetdocument'),
        ),
        migrations.CreateModel(
            name='VetAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='vetversion',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='vet_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='vetnorm',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 0), ('rate__isnull', True), _connector='OR'), name='vet_nonnegative_norm'),
        ),
        migrations.AddConstraint(
            model_name='vetmovement',
            constraint=models.UniqueConstraint(fields=('document', 'product'), name='vet_unique_movement'),
        ),
    ]
